name: GitHub Metrics

on:
  schedule: [{cron: "0 12 * * *"}] # каждый день в 12:00 UTC
  workflow_dispatch: # позволяет вручную запускать

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Fristaylo
          base: ""
          filename: github-metrics.svg
          plugin_languages: yes
          plugin_languages.indepth: yes
          plugin_languages.sections: most-used
          plugin_languages.limit: 10
          plugin_languages.recent_load: 300
          plugin_languages.analysis_timeout: 300
